force-app/main/default/objects/Account/fields/VIN_Number__c.field-meta.xml
<CustomField>
    <fullName>VIN_Number__c</fullName>
    <label>VIN Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <label>Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <label>Service Contract</label>
    <referenceTo>Service_Contract__c</referenceTo>
    <relationshipLabel>Coverages</relationshipLabel>
    <relationshipName>Coverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <label>Repair</label>
    <nameField>
        <displayFormat>RPN-{00000}</displayFormat>
        <label>Repair Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repairs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <referenceTo>Coverage__c</referenceTo>
    <relationshipLabel>Repairs</relationshipLabel>
    <relationshipName>Repairs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Repairs</relationshipLabel>
    <relationshipName>Repairs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <label>Service Contract</label>
    <referenceTo>Service_Contract__c</referenceTo>
    <relationshipLabel>Repairs</relationshipLabel>
    <relationshipName>Repairs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Contract__c/Service_Contract__c.object-meta.xml
<CustomObject>
    <label>Service Contract</label>
    <nameField>
        <label>Service Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Contract__c/fields/Current_Odometer__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer__c</fullName>
    <label>Current Odometer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Contract__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Contract__c/fields/VIN_Number__c.field-meta.xml
<CustomField>
    <fullName>VIN_Number__c</fullName>
    <formula>Customer_Account__r.VIN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/returnAcc.cls
/**
 * @description       : 
 * @author            : Vrushabh Uprikar
 * @group             : 
 * @last modified on  : 03-02-2021
 * @last modified by  : Vrushabh Uprikar
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   03-01-2021   Vrushabh Uprikar   Initial Version
**/
public inherited sharing class returnAcc 
{  
    
     

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccList(String accName, String vinNumb)
    {
            List<Account> listAcc = new List<Account>() ;
            String str ='%'+accName+'%';
            String num ='%'+vinNumb+'%';
            listAcc = [Select Id, Name , Email__c, BillingAddress, Phone, VIN_Number__c from 
            Account where Name like : str AND VIN_Number__c like : num limit 1];
            return listAcc;        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Service_Contract__c> getServiceContract(String accName)
    {
        String acc ='%'+accName+'%';
        List<Service_Contract__c> listServiceContract = [Select Id, Name,VIN_Number__c, Dealer_Address__c, Current_Odometer__c , Customer_Account__r.name 
        from Service_Contract__c Where Customer_Account__r.name like :acc];
        return listServiceContract;
        
    }
    //SELECT Description__c, Name, Service_Contract__c FROM Coverage__c WHERE Service_Contract__r.Name LIKE '%Servicing %'

    @AuraEnabled(cacheable=true)
    public static List<Coverage__c> getCoverage(String vinNumb)
    {
        String str ='%'+vinNumb+'%';
        List<Coverage__c> listContracts=[SELECT Description__c, Name, Service_Contract__r.Name FROM 
        Coverage__c WHERE Service_Contract__r.VIN_Number__c like: str];        
        return listContracts;
        
    }

    // by coverage name
    @AuraEnabled(cacheable=true)
    public static List<Repair__c> getRepair(String coverageName)
    {
        List<Repair__c> listRepair=[SELECT Name, Service_Contract__r.Name, Customer__r.Name, Coverage__r.Name,
        Description__c, Status__c FROM  Repair__c Where Coverage__r.Name =: coverageName];        
        return listRepair;
        
    }
}